version: '2'
services:
  client:
    build: ./front-end
    ports:
      - '3000:3000'
    depends_on:
      - server
  server:
    restart: on-failure
    build: ./backend
    ports:
      - '8080:8080'
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: secretsauce
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/sample.sql:/docker-entrypoint-initdb.d/sample.sql
